// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oocheyfjhnxvyanjpxia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vY2hleWZqaG54dnlhbmpweGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NzU3NTgsImV4cCI6MjA3NDE1MTc1OH0.aTjR_Jmea3HTyNs1wcVoeiQiI7wXc1vs_W_6DwIPEEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});